name: csv
version: 3.0.0
author: Christian Loitsch <christian@loitsch.com>
description: |-
  A codec to transform between a string and a list of values.

  The string must be comma (configurable) separated values.
homepage: https://github.com/close2/csv
documentation: https://github.com/close2/csv
dev_dependencies:
  unittest: '>=0.11.0+5 <0.12.0'
